<?php
namespace backend\extensions;


use Yii;
use yii\web\Controller;


/**
 * Site controller
 */
class BaseController extends Controller
{

   protected $title = "";

   protected $whiteSkip = [
        "company/index/login"
   ];//免登陆接口白名单设置

   public function init() {
       parent::init(); // TODO: Change the autogenerated stub
       if ( !in_array(Yii::$app->requestedRoute,$this->whiteSkip)){
           //是否登陆的权限认证
           $isLogin = Yii::$app->backService->UserService->checkLogin();
           if (!$isLogin) {
               $this->redirect(['/company/index/login'])->send();
               Yii::$app->end();
           }
       }
   }


   public function render($view, $params = [])
   {
       $module = Yii::$app->controller->module->id;
       $controller = Yii::$app->controller->id;
       $action = Yii::$app->controller->action->id;
       $viewModel = Yii::$app->view;
       $viewModel->params['title']= $this->title;
       $viewModel->params['js_tpl']= $module."_".$controller."_".$action;
       $userInfo = Yii::$app->backService->UserService->getUserInfo();
       $viewModel->params['username']= $userInfo['username'];
       return parent::render($view, $params); // TODO: Change the autogenerated stub
   }
}
